language: perl
perl:
  - 5.16
  - 5.14
before_install: cpanm Module::CPANfile
install: cpanm --with-develop --installdeps --notest .
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
